spring:
  application:
    name: MyDemo
  cloud:
    function:
      definition: simpleMessage
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        outputChannel:
          destination: custom-topic
        simpleMessage-in-0:
          destination: custom-topic
#      poller:
#        fixed-delay: 500

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
